
import type { DefineComponent, SlotsType } from 'vue'
type IslandComponent<T extends DefineComponent> = T & DefineComponent<{}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, SlotsType<{ fallback: { error: unknown } }>>
interface _GlobalComponents {
      'AboutUsFeatures': typeof import("../components/AboutUs/Features.vue")['default']
    'AboutUsHeading': typeof import("../components/AboutUs/Heading.vue")['default']
    'AboutUsInfo': typeof import("../components/AboutUs/Info.vue")['default']
    'AboutUsLocations': typeof import("../components/AboutUs/Locations.vue")['default']
    'AboutUsMissionVision': typeof import("../components/AboutUs/MissionVision.vue")['default']
    'AboutUsOwners': typeof import("../components/AboutUs/Owners.vue")['default']
    'AboutUsSubscribe': typeof import("../components/AboutUs/Subscribe.vue")['default']
    'ContactUsContent': typeof import("../components/ContactUs/Content.vue")['default']
    'ContactUsHeading': typeof import("../components/ContactUs/Heading.vue")['default']
    'ContactUsMap': typeof import("../components/ContactUs/Map.vue")['default']
    'HomeAbout': typeof import("../components/Home/About.vue")['default']
    'HomeBenefits': typeof import("../components/Home/Benefits.vue")['default']
    'HomeHeroSlider': typeof import("../components/Home/HeroSlider.vue")['default']
    'HomeSlider': typeof import("../components/Home/Slider.vue")['default']
    'HomeSubscribe': typeof import("../components/Home/Subscribe.vue")['default']
    'HomeTestimonial': typeof import("../components/Home/Testimonial.vue")['default']
    'ProductsContent': typeof import("../components/Products/Content.vue")['default']
    'Footer': typeof import("../components/footer.vue")['default']
    'Navbar': typeof import("../components/navbar.vue")['default']
    'NuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'NuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'NuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'ClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'DevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'ServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'NuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'NuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'NuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'NuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'NuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'NuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'NuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'NoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'Link': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'Base': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'Title': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'Meta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'Style': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'Head': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'Html': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'Body': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'NuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
      'LazyAboutUsFeatures': typeof import("../components/AboutUs/Features.vue")['default']
    'LazyAboutUsHeading': typeof import("../components/AboutUs/Heading.vue")['default']
    'LazyAboutUsInfo': typeof import("../components/AboutUs/Info.vue")['default']
    'LazyAboutUsLocations': typeof import("../components/AboutUs/Locations.vue")['default']
    'LazyAboutUsMissionVision': typeof import("../components/AboutUs/MissionVision.vue")['default']
    'LazyAboutUsOwners': typeof import("../components/AboutUs/Owners.vue")['default']
    'LazyAboutUsSubscribe': typeof import("../components/AboutUs/Subscribe.vue")['default']
    'LazyContactUsContent': typeof import("../components/ContactUs/Content.vue")['default']
    'LazyContactUsHeading': typeof import("../components/ContactUs/Heading.vue")['default']
    'LazyContactUsMap': typeof import("../components/ContactUs/Map.vue")['default']
    'LazyHomeAbout': typeof import("../components/Home/About.vue")['default']
    'LazyHomeBenefits': typeof import("../components/Home/Benefits.vue")['default']
    'LazyHomeHeroSlider': typeof import("../components/Home/HeroSlider.vue")['default']
    'LazyHomeSlider': typeof import("../components/Home/Slider.vue")['default']
    'LazyHomeSubscribe': typeof import("../components/Home/Subscribe.vue")['default']
    'LazyHomeTestimonial': typeof import("../components/Home/Testimonial.vue")['default']
    'LazyProductsContent': typeof import("../components/Products/Content.vue")['default']
    'LazyFooter': typeof import("../components/footer.vue")['default']
    'LazyNavbar': typeof import("../components/navbar.vue")['default']
    'LazyNuxtWelcome': typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
    'LazyNuxtLayout': typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
    'LazyNuxtErrorBoundary': typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
    'LazyClientOnly': typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
    'LazyDevOnly': typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
    'LazyServerPlaceholder': typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
    'LazyNuxtLink': typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
    'LazyNuxtLoadingIndicator': typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
    'LazyNuxtRouteAnnouncer': typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
    'LazyNuxtIsland': typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
    'LazyNuxtImg': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
    'LazyNuxtPicture': typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
    'LazyNuxtPage': typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
    'LazyNoScript': typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
    'LazyLink': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
    'LazyBase': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
    'LazyTitle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
    'LazyMeta': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
    'LazyStyle': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
    'LazyHead': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
    'LazyHtml': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
    'LazyBody': typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
    'LazyNuxtRouteAnnouncer': IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
}

declare module '@vue/runtime-core' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module '@vue/runtime-dom' {
  export interface GlobalComponents extends _GlobalComponents { }
}

declare module 'vue' {
  export interface GlobalComponents extends _GlobalComponents { }
}

export const AboutUsFeatures: typeof import("../components/AboutUs/Features.vue")['default']
export const AboutUsHeading: typeof import("../components/AboutUs/Heading.vue")['default']
export const AboutUsInfo: typeof import("../components/AboutUs/Info.vue")['default']
export const AboutUsLocations: typeof import("../components/AboutUs/Locations.vue")['default']
export const AboutUsMissionVision: typeof import("../components/AboutUs/MissionVision.vue")['default']
export const AboutUsOwners: typeof import("../components/AboutUs/Owners.vue")['default']
export const AboutUsSubscribe: typeof import("../components/AboutUs/Subscribe.vue")['default']
export const ContactUsContent: typeof import("../components/ContactUs/Content.vue")['default']
export const ContactUsHeading: typeof import("../components/ContactUs/Heading.vue")['default']
export const ContactUsMap: typeof import("../components/ContactUs/Map.vue")['default']
export const HomeAbout: typeof import("../components/Home/About.vue")['default']
export const HomeBenefits: typeof import("../components/Home/Benefits.vue")['default']
export const HomeHeroSlider: typeof import("../components/Home/HeroSlider.vue")['default']
export const HomeSlider: typeof import("../components/Home/Slider.vue")['default']
export const HomeSubscribe: typeof import("../components/Home/Subscribe.vue")['default']
export const HomeTestimonial: typeof import("../components/Home/Testimonial.vue")['default']
export const ProductsContent: typeof import("../components/Products/Content.vue")['default']
export const Footer: typeof import("../components/footer.vue")['default']
export const Navbar: typeof import("../components/navbar.vue")['default']
export const NuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const NuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const NuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const ClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const DevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const ServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const NuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const NuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const NuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const NuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const NuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const NuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const NuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const NoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const Link: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const Base: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const Title: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const Meta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const Style: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const Head: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const Html: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const Body: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const NuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>
export const LazyAboutUsFeatures: typeof import("../components/AboutUs/Features.vue")['default']
export const LazyAboutUsHeading: typeof import("../components/AboutUs/Heading.vue")['default']
export const LazyAboutUsInfo: typeof import("../components/AboutUs/Info.vue")['default']
export const LazyAboutUsLocations: typeof import("../components/AboutUs/Locations.vue")['default']
export const LazyAboutUsMissionVision: typeof import("../components/AboutUs/MissionVision.vue")['default']
export const LazyAboutUsOwners: typeof import("../components/AboutUs/Owners.vue")['default']
export const LazyAboutUsSubscribe: typeof import("../components/AboutUs/Subscribe.vue")['default']
export const LazyContactUsContent: typeof import("../components/ContactUs/Content.vue")['default']
export const LazyContactUsHeading: typeof import("../components/ContactUs/Heading.vue")['default']
export const LazyContactUsMap: typeof import("../components/ContactUs/Map.vue")['default']
export const LazyHomeAbout: typeof import("../components/Home/About.vue")['default']
export const LazyHomeBenefits: typeof import("../components/Home/Benefits.vue")['default']
export const LazyHomeHeroSlider: typeof import("../components/Home/HeroSlider.vue")['default']
export const LazyHomeSlider: typeof import("../components/Home/Slider.vue")['default']
export const LazyHomeSubscribe: typeof import("../components/Home/Subscribe.vue")['default']
export const LazyHomeTestimonial: typeof import("../components/Home/Testimonial.vue")['default']
export const LazyProductsContent: typeof import("../components/Products/Content.vue")['default']
export const LazyFooter: typeof import("../components/footer.vue")['default']
export const LazyNavbar: typeof import("../components/navbar.vue")['default']
export const LazyNuxtWelcome: typeof import("../node_modules/nuxt/dist/app/components/welcome")['default']
export const LazyNuxtLayout: typeof import("../node_modules/nuxt/dist/app/components/nuxt-layout")['default']
export const LazyNuxtErrorBoundary: typeof import("../node_modules/nuxt/dist/app/components/nuxt-error-boundary")['default']
export const LazyClientOnly: typeof import("../node_modules/nuxt/dist/app/components/client-only")['default']
export const LazyDevOnly: typeof import("../node_modules/nuxt/dist/app/components/dev-only")['default']
export const LazyServerPlaceholder: typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']
export const LazyNuxtLink: typeof import("../node_modules/nuxt/dist/app/components/nuxt-link")['default']
export const LazyNuxtLoadingIndicator: typeof import("../node_modules/nuxt/dist/app/components/nuxt-loading-indicator")['default']
export const LazyNuxtRouteAnnouncer: typeof import("../node_modules/nuxt/dist/app/components/nuxt-route-announcer")['default']
export const LazyNuxtIsland: typeof import("../node_modules/nuxt/dist/app/components/nuxt-island")['default']
export const LazyNuxtImg: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtImg']
export const LazyNuxtPicture: typeof import("../node_modules/nuxt/dist/app/components/nuxt-stubs")['NuxtPicture']
export const LazyNuxtPage: typeof import("../node_modules/nuxt/dist/pages/runtime/page")['default']
export const LazyNoScript: typeof import("../node_modules/nuxt/dist/head/runtime/components")['NoScript']
export const LazyLink: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Link']
export const LazyBase: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Base']
export const LazyTitle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Title']
export const LazyMeta: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Meta']
export const LazyStyle: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Style']
export const LazyHead: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Head']
export const LazyHtml: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Html']
export const LazyBody: typeof import("../node_modules/nuxt/dist/head/runtime/components")['Body']
export const LazyNuxtRouteAnnouncer: IslandComponent<typeof import("../node_modules/nuxt/dist/app/components/server-placeholder")['default']>

export const componentNames: string[]
